---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Master Template'
Parameters:
  ClusterName:
    Description: The cluster name that will be used to create the EKS cluster.
    Type: String

  VpcBlock:
    Type: String
    Default: 192.168.0.0/16
    Description: The CIDR range for the VPC. This should be a valid private (RFC 1918) CIDR range.

  Subnet01Block:
    Type: String
    Default: 192.168.64.0/18
    Description: CidrBlock for subnet 01 within the VPC

  Subnet02Block:
    Type: String
    Default: 192.168.128.0/18
    Description: CidrBlock for subnet 02 within the VPC

  Subnet03Block:
    Type: String
    Default: 192.168.192.0/18
    Description: CidrBlock for subnet 03 within the VPC

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Can contain only ASCII characters.

  NodeImageId:
    Type: AWS::EC2::Image::Id
    Description: AMI id for the node instances. Id "ami-73a6e20b" is in us-west-2 and "ami-dea4d5a1" is in us-east-1.
    Default: ami-73a6e20b
    AllowedValues:
    - ami-73a6e20b
    - ami-dea4d5a1

  NodeInstanceType:
    Description: EC2 instance type for the node instances
    Type: String
    Default: t2.medium
    AllowedValues:
    - t2.small
    - t2.medium
    - t2.large
    - t2.xlarge
    - t2.2xlarge
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.10xlarge
    - m5.large
    - m5.xlarge
    - m5.2xlarge
    - m5.4xlarge
    - m5.12xlarge
    - m5.24xlarge
    - c4.large
    - c4.xlarge
    - c4.2xlarge
    - c4.4xlarge
    - c4.8xlarge
    - c5.large
    - c5.xlarge
    - c5.2xlarge
    - c5.4xlarge
    - c5.9xlarge
    - c5.18xlarge
    - i3.large
    - i3.xlarge
    - i3.2xlarge
    - i3.4xlarge
    - i3.8xlarge
    - i3.16xlarge
    - r3.xlarge
    - r3.2xlarge
    - r3.4xlarge
    - r3.8xlarge
    - r4.large
    - r4.xlarge
    - r4.2xlarge
    - r4.4xlarge
    - r4.8xlarge
    - r4.16xlarge
    - x1.16xlarge
    - x1.32xlarge
    - p2.xlarge
    - p2.8xlarge
    - p2.16xlarge
    - p3.2xlarge
    - p3.8xlarge
    - p3.16xlarge
    ConstraintDescription: must be a valid EC2 instance type

  NodeAutoScalingGroupMinSize:
    Type: Number
    Description: Minimum size of Node Group ASG.
    Default: 1

  NodeAutoScalingGroupMaxSize:
    Type: Number
    Description: Maximum size of Node Group ASG.
    Default: 3

  NodeGroupName:
    Description: Unique identifier for the Node Group.
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "EKS Cluster"
        Parameters:
          - ClusterName
      -
        Label:
          default: "EKS Cluster Configuration"
        Parameters:
          - VpcBlock
          - Subnet01Block
          - Subnet02Block
          - Subnet03Block
      -
        Label:
          default: "Worker Node Configuration"
        Parameters:
          - NodeGroupName
          - NodeAutoScalingGroupMinSize
          - NodeAutoScalingGroupMaxSize
          - NodeInstanceType
          - NodeImageId
          - KeyName
  
Resources:
  EKSVPC:
    Properties:
      Parameters:
        VpcBlock: !Ref 'VpcBlock'
        Subnet01Block: !Ref 'Subnet01Block'
        Subnet02Block: !Ref 'Subnet02Block'
        Subnet03Block: !Ref 'Subnet03Block'
      TemplateURL: 'https://s3-us-west-2.amazonaws.com/eks-quickstart-demo/v2/amazon-eks-vpc.yaml'
    Type: AWS::CloudFormation::Stack
  EKSServiceRole:
    Properties:
      TemplateURL: 'https://s3-us-west-2.amazonaws.com/eks-quickstart-demo/v2/amazon-eks-service-role.yaml'
    Type: AWS::CloudFormation::Stack
  EKSCluster:
    Properties:
      Parameters:
        ClusterName: !Ref 'ClusterName'
        VPC: !GetAtt [EKSVPC, Outputs.VpcId]
        SubnetIds: !GetAtt [EKSVPC, Outputs.SubnetIds]
        RoleArn: !GetAtt [EKSServiceRole, Outputs.RoleArn]
        SecurityGroups: !GetAtt [EKSVPC, Outputs.SecurityGroups]
      TemplateURL: 'https://s3-us-west-2.amazonaws.com/eks-quickstart-demo/v2/amazon-eks-cluster.yaml'
    DependsOn: [EKSVPC]
    Type: AWS::CloudFormation::Stack
  EKSNodes:
    Properties:
      Parameters:
        ClusterName: !Ref 'ClusterName'
        KeyName: !Ref 'KeyName'
        NodeImageId: !Ref 'NodeImageId'
        NodeInstanceType: !Ref 'NodeInstanceType'
        NodeAutoScalingGroupMinSize: !Ref 'NodeAutoScalingGroupMinSize'
        NodeAutoScalingGroupMaxSize: !Ref 'NodeAutoScalingGroupMaxSize'
        NodeGroupName: !Ref 'NodeGroupName'
        ClusterControlPlaneSecurityGroup: !GetAtt [EKSVPC, Outputs.SecurityGroups]
        VpcId: !GetAtt [EKSVPC, Outputs.VpcId]
        Subnets: !GetAtt [EKSVPC, Outputs.SubnetIds]
      TemplateURL: 'https://s3-us-west-2.amazonaws.com/eks-quickstart-demo/v2/amazon-eks-nodegroup.yaml'
    DependsOn: [EKSCluster]
    Type: AWS::CloudFormation::Stack

